### ISSUE TITLE
About Sony Implementation

### ISSUE THREAD

**Issue by Huanxi2018** [Kovelja009/mixed_precision_dnn_pytorch#2]
Excuse me, may I take a few minutes of your time again？
I'd like to ask you if you can run the code of Sony correctly. Because of the old version of nnabla-ext-cuda101 that I couldn't download (.whl and so on) directly, I can't run that implementation correctly. Do you have any ideas?
Looking forward to your reply.

**Comment by Kovelja009** [comment]
Hi, sorry for the late reply. What do you mean by **_correctly_** running the code. I have run it in the past to see how it works, but unfortunately it has passed quite some time from then, so I don't remember vividly, the only thing I do remember is that somehow I managed to run the code in the end.
